// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rhprbxmdcgsycypoiexg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJocHJieG1kY2dzeWN5cG9pZXhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwOTEyODgsImV4cCI6MjA2MTY2NzI4OH0.gfM8M3QSbk-udAvDZFBNTgwLBdM__poC_rAGSsYZmDg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);